// <auto-generated />
namespace HomeBird.DataBase.Ef6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SaleNewFileds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SaleNewFileds));
        
        string IMigrationMetadata.Id
        {
            get { return "201610301834113_SaleNewFileds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
